### ISSUE TITLE
Possibility to give multiple events catalogue in download config file (eventws parameter) ?

### ISSUE THREAD

**Issue by margauxBscti** [rizac/stream2segment#22]
Hello,

Finally I installed stream2segment on Windows and all working well. 

We wonder if it's possible to define differents catalogue events in eventws parameter, as for dataws, It is an option of stream2segment download function ? 
When I try to give several catalogues such as in the example below it doesn't work and give the error : Error: Invalid type for "eventws": string required.

Example:
eventws: 
 - 'http://www.isc.ac.uk/fdsnws/event/1/query'
 - 'http://www.seismicportal.eu/fdsnws/event/1/query'

I try this too:
eventws: [ "http://www.isc.ac.uk/fdsnws/event/1/query" , "https://api.franceseisme.fr/fdsnws/event/1/query" ]

Thank you, and sorry to bother you again.

Margaux

**Comment by rizac** [comment]
Hi, no problem this is the right place to bother ;-)

you can't do what you want because there's an easy workaround. Simply perform several downloads.
However, instead of writing two almost identical YAML configs and running them (which is always possible in any case), I suggest you an easier workaround. If you type
```
    s2s download --help
```
you will see that you can provide the `--eventws` option. If provided, it will overwrite the eventws of the config. So this should work:

```
s2s download -c <config.yaml>; s2s download -c <config.yaml> --eventws <Catalog2URL>; 
```

in the first download, the event catalog URL will be the one written in the config.yaml. Alternatively
you can be more explicit (the following will not read whatever eventws you have in the config):
```
s2s download -c <config.yaml> --eventws <Catalog1URL>; s2s download -c <config.yaml> --eventws <Catalog2URL>; 
```

Hope I have ben clear. If it doesn't work let me know.

R

**Comment by margauxBscti** [comment]
Hi, thank you for your answer !

Yes you have been clear :) 
We could download the database we wanted. 

Have a nice day !

Margaux
